name: Python CI

on:
  push:
    branches:
      - main  # Runs the workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Runs the workflow on pull requests targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Checks out the repository code

    - name: Set up Python
      uses: actions/setup-python@v4  # Sets up Python
      with:
        python-version: '3.10'  # Specify your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: pytest tests/